version: "3.8" # optional since v1.27.0

services:
    mysql:
        image: mysql/mysql-server
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kuclap
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpwd
        ports:
            - 3306:3306

    backend:
        build: ./backend
        environment:
            - NODE_ENV=development
            - PORT=3000
        volumes:
            - .:/usr/app/backend
        command:
            - /bin/bash
            - -c
            - |
                cd backend
                npm install
                npm start
        ports:
            - 3000:3000
        depends_on:
            - mysql
    
    frontend:
        build: ./frontend
        volumes:
            - .:/usr/app/frontend
        command: 
            - /bin/bash
            - -c
            - |
                cd frontend
                npm install
                npm start
        ports:
            - 8080:8080
        depends_on:
            - backend
            - mysql
